POST http://localhost:8080/start
Content-Type: application/json

{
  "name": "John",
  "surname": "Doe",
  "email": "john@example.com",
  "password": "Strong1234!",
  "repeatPassword": "Strong1234!"
}
